version: '2'

services:
 neo4j:
  image: neo4j:3.1.1-enterprise
  ports:
   - "7474:7474"
   - "7687:7687"
  expose:
   - "7687"
   - "7474"
  environment:
   - NEO4J_AUTH=none

 valuation:
  build: ./build
  image: valuation-app
  ports:
   - "9090:9090"
  links:
    - neo4j