pipeline:
  checkout:
    image: busybox:latest
    commands:
      - echo "nexusUrl=https://nexus.acuo.com" > gradle.properties
      - echo "nexusUsername=deployer" >> gradle.properties
      - echo "nexusPassword=${NEXUS_PASSWORD}"  >> gradle.properties 
  
  build:
    image: java:8
    commands:
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - ./gradlew snapshot dockerPushImage -Pprofile=docker  -x test -x integrationTest

  